import { MigrationInterface, QueryRunner } from "typeorm";

export class CompleteInitialMigration1762075821855 implements MigrationInterface {
    name = 'CompleteInitialMigration1762075821855'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "street" character varying, "city" character varying, "state" character varying, "country" character varying, "zipCode" character varying, "latitude" double precision, "longitude" double precision, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."job_type_enum" AS ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'REMOTE')`);
        await queryRunner.query(`CREATE TYPE "public"."job_joblevel_enum" AS ENUM('ENTRY', 'MID', 'SENIOR', 'EXECUTIVE')`);
        await queryRunner.query(`CREATE TYPE "public"."job_worktype_enum" AS ENUM('ONSITE', 'REMOTE', 'HYBRID')`);
        await queryRunner.query(`CREATE TYPE "public"."job_status_enum" AS ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', 'EXPIRED', 'DELETED')`);
        await queryRunner.query(`CREATE TABLE "job" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "title" character varying NOT NULL, "department" character varying NOT NULL, "location" character varying NOT NULL, "salary" character varying NOT NULL, "type" "public"."job_type_enum" NOT NULL, "deadline" TIMESTAMP NOT NULL, "description" text NOT NULL, "shortDescription" text NOT NULL, "responsibilities" text NOT NULL, "requirements" text NOT NULL, "benefits" text NOT NULL, "skills" text array NOT NULL, "experience" character varying NOT NULL, "education" character varying NOT NULL, "jobLevel" "public"."job_joblevel_enum" NOT NULL, "workType" "public"."job_worktype_enum" NOT NULL, "industry" character varying NOT NULL, "companyDescription" text NOT NULL, "status" "public"."job_status_enum" NOT NULL DEFAULT 'DRAFT', "companyId" uuid NOT NULL, "cvAnalysisPrompt" text, "interviewPrompt" text, "aiSecondInterviewPrompt" text, "interviewLanguage" character varying NOT NULL DEFAULT 'english', "featured" boolean NOT NULL DEFAULT false, "applicants" integer NOT NULL DEFAULT '0', "views" integer NOT NULL DEFAULT '0', "featuredJobs" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "postedById" uuid NOT NULL, CONSTRAINT "UQ_bb1c7d9ea827ecf0c54d0794461" UNIQUE ("slug"), CONSTRAINT "PK_98ab1c14ff8d1cf80d18703b92f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb1c7d9ea827ecf0c54d079446" ON "job" ("slug") `);
        await queryRunner.query(`CREATE TABLE "company" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "website" character varying, "email" character varying, "phone" character varying, "logo" character varying, "industry" character varying, "size" character varying, "founded" date, "location" character varying, "addressId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_3737905699894299444476dd79" UNIQUE ("addressId"), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_experience" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidateProfileId" uuid NOT NULL, "company" character varying NOT NULL, "position" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date, "description" text, "isCurrent" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d4bef63ad6da7ec327515c121bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "education" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidateProfileId" uuid NOT NULL, "institution" character varying NOT NULL, "degree" character varying NOT NULL, "fieldOfStudy" character varying, "startDate" date, "endDate" date, "grade" character varying, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bf3d38701b3030a8ad634d43bd6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cv" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidateProfileId" uuid NOT NULL, "fileName" character varying NOT NULL, "fileUrl" character varying NOT NULL, "fileSize" integer, "mimeType" character varying, "isPrimary" boolean NOT NULL DEFAULT false, "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4ddf7891daf83c3506efa503bb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_profile_availability_enum" AS ENUM('AVAILABLE', 'NOT_AVAILABLE', 'LOOKING')`);
        await queryRunner.query(`CREATE TYPE "public"."candidate_profile_preferredworktype_enum" AS ENUM('ONSITE', 'REMOTE', 'HYBRID')`);
        await queryRunner.query(`CREATE TABLE "candidate_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying, "phone" character varying, "location" character varying, "bio" text, "skills" text array NOT NULL DEFAULT '{}', "experience" character varying, "education" character varying, "linkedinUrl" character varying, "githubUrl" character varying, "portfolioUrl" character varying, "resumeUrl" character varying, "availability" "public"."candidate_profile_availability_enum", "salaryExpectation" character varying, "preferredWorkType" "public"."candidate_profile_preferredworktype_enum", "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab092d6b881f23c10ff1b801829" UNIQUE ("userId"), CONSTRAINT "REL_ab092d6b881f23c10ff1b80182" UNIQUE ("userId"), CONSTRAINT "PK_404029cefcd04a9d68f13f9d8e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_candidate_profile_phone" ON "candidate_profile" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_candidate_profile_availability" ON "candidate_profile" ("availability") `);
        await queryRunner.query(`CREATE TYPE "public"."user_usertype_enum" AS ENUM('SYSTEM', 'CANDIDATE', 'BUSINESS', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userType" "public"."user_usertype_enum" NOT NULL, "password" character varying, "email" character varying, "name" character varying, "phone" character varying, "avatar" character varying, "isActive" boolean NOT NULL DEFAULT true, "companyId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "api_key" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "name" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "UQ_fb080786c16de6ace7ed0b69f7d" UNIQUE ("key"), CONSTRAINT "PK_b1bd840641b8acbaad89c3d8d11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "security_log" ("id" character varying NOT NULL, "type" character varying NOT NULL, "userId" character varying, "ipHash" character varying NOT NULL, "userAgentHash" character varying, "details" json NOT NULL, "severity" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_efed13f4d5863b4dd080994b486" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "live_kit_room" ("id" character varying NOT NULL, "name" character varying NOT NULL, "metadata" json, "createdBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dec6236278002920979985aba8b" UNIQUE ("name"), CONSTRAINT "PK_5db8ccc7afe73509bf9bf3e6bf2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "saved_job" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "jobId" uuid NOT NULL, "savedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eec7a26a4f0a651ab3d63c2a4a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e78c19878d2e6143e4c6140c81" ON "saved_job" ("userId", "jobId") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum" AS ENUM('SUCCESS', 'WARNING', 'INFO', 'ERROR')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_category_enum" AS ENUM('APPLICATION', 'INTERVIEW', 'SYSTEM', 'CANDIDATE', 'OFFER')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" character varying NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "type" "public"."notification_type_enum" NOT NULL DEFAULT 'INFO', "category" "public"."notification_category_enum" NOT NULL, "read" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "readAt" TIMESTAMP, "userId" uuid NOT NULL, "metadata" json, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "emailNotifications" boolean NOT NULL DEFAULT true, "emailApplicationUpdates" boolean NOT NULL DEFAULT true, "emailInterviewReminders" boolean NOT NULL DEFAULT true, "emailJobRecommendations" boolean NOT NULL DEFAULT true, "emailNewsletter" boolean NOT NULL DEFAULT true, "smsNotifications" boolean NOT NULL DEFAULT false, "smsApplicationUpdates" boolean NOT NULL DEFAULT false, "smsInterviewReminders" boolean NOT NULL DEFAULT false, "pushNotifications" boolean NOT NULL DEFAULT true, "pushApplicationUpdates" boolean NOT NULL DEFAULT true, "pushInterviewReminders" boolean NOT NULL DEFAULT true, "pushNewMessages" boolean NOT NULL DEFAULT true, "marketingEmails" boolean NOT NULL DEFAULT false, "partnerOffers" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5a8ffc3b89343043c9440d631e2" UNIQUE ("userId"), CONSTRAINT "REL_5a8ffc3b89343043c9440d631e" UNIQUE ("userId"), CONSTRAINT "PK_d131abd7996c475ef768d4559ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "application_note" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "userId" uuid NOT NULL, "note" text NOT NULL, "isPrivate" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f566bcb8dbe1afd09c325b23fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."application_status_enum" AS ENUM('PENDING', 'REVIEWED', 'SHORTLISTED', 'INTERVIEWED', 'OFFERED', 'HIRED', 'ANALYZED', 'REJECTED', 'WITHDRAWN')`);
        await queryRunner.query(`CREATE TABLE "application" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jobId" uuid NOT NULL, "candidateId" uuid NOT NULL, "status" "public"."application_status_enum" NOT NULL DEFAULT 'PENDING', "appliedAt" TIMESTAMP NOT NULL DEFAULT now(), "coverLetter" text, "resumeUrl" character varying, "expectedSalary" character varying, "noticePeriod" character varying, "cvAnalysisScore" numeric(5,2), "cvScore" numeric(5,2), "firstInterviewScore" numeric(5,2), "secondInterviewScore" numeric(5,2), "finalScore" numeric(5,2), "cvAnalysisResults" json, "analyzedAt" TIMESTAMP, "aiCvRecommendations" text, "aiInterviewRecommendations" text, "aiSecondInterviewRecommendations" text, "recommendationsGeneratedAt" TIMESTAMP, "companyNotes" text, "source" character varying, "notes" text, "applicantName" character varying, "applicantEmail" character varying, "applicantPhone" character varying, "applicantLinkedin" character varying, "aiAnalysis" json, "interviewScheduled" boolean NOT NULL DEFAULT false, "reviewedAt" TIMESTAMP, "interviewScheduledAt" TIMESTAMP, "interviewedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "acceptedAt" TIMESTAMP, "interviewLanguage" character varying NOT NULL DEFAULT 'english', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_569e0c3e863ebdf5f2408ee1670" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "livekit_rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomName" character varying NOT NULL, "roomSid" character varying NOT NULL, "roomPassword" character varying NOT NULL, "passwordExpiresAt" TIMESTAMP NOT NULL, "passwordUsed" boolean NOT NULL DEFAULT false, "applicationId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_841f7688e5585f664b96c9dedbb" UNIQUE ("roomName"), CONSTRAINT "PK_e2ae2e559a4352e908688a22fe0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."interview_type_enum" AS ENUM('VIDEO', 'PHONE', 'IN_PERSON')`);
        await queryRunner.query(`CREATE TYPE "public"."interview_status_enum" AS ENUM('SCHEDULED', 'STARTED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')`);
        await queryRunner.query(`CREATE TABLE "interview" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "scheduledAt" TIMESTAMP, "duration" integer, "type" "public"."interview_type_enum" NOT NULL DEFAULT 'VIDEO', "status" "public"."interview_status_enum" NOT NULL DEFAULT 'SCHEDULED', "notes" text, "feedback" text, "rating" integer, "aiAnalysis" json, "recordingUrl" character varying, "roomId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_44c49a4feadefa5c6fa78bfb7d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transcript" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "interviewId" uuid NOT NULL, "content" text NOT NULL, "speaker" character varying NOT NULL, "timestamp" TIMESTAMP NOT NULL, "confidence" double precision, "language" character varying NOT NULL DEFAULT 'english', "sequenceNumber" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b5b7a9bdb53103727ced1eec10e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."database_backups_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'DELETED')`);
        await queryRunner.query(`CREATE TYPE "public"."database_backups_type_enum" AS ENUM('MANUAL', 'SCHEDULED_DAILY', 'SCHEDULED_WEEKLY', 'SCHEDULED_MONTHLY')`);
        await queryRunner.query(`CREATE TABLE "database_backups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fileName" character varying NOT NULL, "s3Key" character varying NOT NULL, "s3Url" character varying NOT NULL, "fileSize" bigint NOT NULL, "status" "public"."database_backups_status_enum" NOT NULL DEFAULT 'PENDING', "type" "public"."database_backups_type_enum" NOT NULL DEFAULT 'MANUAL', "databaseName" character varying, "databaseSize" character varying, "executionTime" integer, "errorMessage" text, "createdBy" uuid, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_453a5e5f858d08f4fde91d0640c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invitation_usertype_enum" AS ENUM('SYSTEM', 'CANDIDATE', 'BUSINESS', 'ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."invitation_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "invitation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "email" character varying, "userType" "public"."invitation_usertype_enum" NOT NULL, "status" "public"."invitation_status_enum" NOT NULL DEFAULT 'PENDING', "invitedById" uuid NOT NULL, "companyId" uuid, "expiresAt" TIMESTAMP, "usedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d23721ee8274af12ae925994257" UNIQUE ("code"), CONSTRAINT "PK_beb994737756c0f18a1c1f8669c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."communication_type_enum" AS ENUM('EMAIL', 'SMS', 'WHATSAPP', 'IN_APP')`);
        await queryRunner.query(`CREATE TYPE "public"."communication_direction_enum" AS ENUM('INBOUND', 'OUTBOUND')`);
        await queryRunner.query(`CREATE TYPE "public"."communication_status_enum" AS ENUM('SENT', 'DELIVERED', 'READ', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "communication" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "candidateId" character varying, "companyId" character varying, "jobId" character varying, "applicationId" uuid, "type" "public"."communication_type_enum" NOT NULL, "direction" "public"."communication_direction_enum" NOT NULL, "content" text NOT NULL, "phoneNumber" character varying, "email" character varying, "whatsappId" character varying, "status" "public"."communication_status_enum" NOT NULL DEFAULT 'SENT', "templateName" character varying, "templateParams" json, "sentAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_392407b9e9100bee1a64e26cd5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."whats_app_message_status_enum" AS ENUM('SENT', 'DELIVERED', 'READ', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "whats_app_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "communicationId" uuid NOT NULL, "messageId" character varying, "status" "public"."whats_app_message_status_enum" NOT NULL DEFAULT 'SENT', "deliveredAt" TIMESTAMP, "readAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c5220a47bc7878e72cb4e313421" UNIQUE ("communicationId"), CONSTRAINT "REL_c5220a47bc7878e72cb4e31342" UNIQUE ("communicationId"), CONSTRAINT "PK_35fcd9935d7d77dcf686b6290a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "used" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_36e929b98372d961bb63bd4b4e9" UNIQUE ("token"), CONSTRAINT "PK_8515e60a2cc41584fa4784f52ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_password_reset_email" ON "password_reset" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_password_reset_token" ON "password_reset" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('LOGIN_SUCCESS', 'LOGIN_FAILURE', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_COMPLETE', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'API_KEY_GENERATED', 'API_KEY_REVOKED', 'API_KEY_INVALID', 'JOB_CREATED', 'JOB_UPDATED', 'JOB_DELETED', 'JOB_PUBLISHED', 'APPLICATION_CREATED', 'APPLICATION_UPDATED', 'APPLICATION_DELETED', 'APPLICATION_STATUS_CHANGED', 'APPLICATION_NOTE_CREATED', 'APPLICATION_NOTE_UPDATED', 'APPLICATION_NOTE_DELETED', 'NOTIFICATION_CREATED', 'NOTIFICATION_READ', 'NOTIFICATION_DELETED', 'BULK_NOTIFICATION_READ', 'RATE_LIMIT_EXCEEDED', 'UNAUTHORIZED_ACCESS', 'FORBIDDEN_ACCESS', 'SECURITY_EVENT', 'BRUTE_FORCE_ATTEMPT', 'INVALID_TOKEN', 'SUSPICIOUS_ACTIVITY', 'SYSTEM_ERROR', 'DATA_EXPORT', 'DATA_IMPORT', 'DATA_DELETION', 'CONFIG_CHANGE')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" character varying NOT NULL, "action" "public"."audit_logs_action_enum" NOT NULL, "userId" character varying, "userEmail" character varying, "resourceType" character varying, "resourceId" character varying, "description" text, "metadata" json, "ipAddress" character varying, "userAgent" character varying, "requestId" character varying, "isSystemAction" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ec936941eb8556fcd7a1f0eae" ON "audit_logs" ("action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_99e589da8f9e9326ee0d01a028" ON "audit_logs" ("userId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD CONSTRAINT "UQ_e78c19878d2e6143e4c6140c81c" UNIQUE ("userId", "jobId")`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_e66170573cabd565dab1132727d" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_49dd92c00fe0d00a40602e2e171" FOREIGN KEY ("postedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company" ADD CONSTRAINT "FK_3737905699894299444476dd79c" FOREIGN KEY ("addressId") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_experience" ADD CONSTRAINT "FK_fe64019bc2a32b29226442f7342" FOREIGN KEY ("candidateProfileId") REFERENCES "candidate_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "education" ADD CONSTRAINT "FK_020a2f7db1c68a2d9eb9fe8c09d" FOREIGN KEY ("candidateProfileId") REFERENCES "candidate_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cv" ADD CONSTRAINT "FK_68b505eded7c9f3add3afe9ff66" FOREIGN KEY ("candidateProfileId") REFERENCES "candidate_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_profile" ADD CONSTRAINT "FK_ab092d6b881f23c10ff1b801829" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_86586021a26d1180b0968f98502" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "api_key" ADD CONSTRAINT "FK_277972f4944205eb29127f9bb6c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD CONSTRAINT "FK_65314280f947dd20a26faf013d2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_job" ADD CONSTRAINT "FK_ceb2154a962ca924a284f15c2e7" FOREIGN KEY ("jobId") REFERENCES "job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_1ced25315eb974b73391fb1c81b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_settings" ADD CONSTRAINT "FK_5a8ffc3b89343043c9440d631e2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_note" ADD CONSTRAINT "FK_546f9c0eff39484764e5fe09290" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_note" ADD CONSTRAINT "FK_5f195f30a2aa3160d902c186c6b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_dbc0341504212f830211b69ba0c" FOREIGN KEY ("jobId") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_56bd5315980a6bcd995a54df8fe" FOREIGN KEY ("candidateId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "livekit_rooms" ADD CONSTRAINT "FK_ee8019347b8669627b2ac90a04e" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interview" ADD CONSTRAINT "FK_35c375805d4e8809adf67f635bb" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transcript" ADD CONSTRAINT "FK_2ede2eb745d7ea378687fcb7b35" FOREIGN KEY ("interviewId") REFERENCES "interview"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation" ADD CONSTRAINT "FK_603764233ba5c97400836665523" FOREIGN KEY ("invitedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitation" ADD CONSTRAINT "FK_757968494b8501e4e3b27860fb0" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication" ADD CONSTRAINT "FK_6fdd6bffa041d6a6b4c0184ccbf" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "whats_app_message" ADD CONSTRAINT "FK_c5220a47bc7878e72cb4e313421" FOREIGN KEY ("communicationId") REFERENCES "communication"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "whats_app_message" DROP CONSTRAINT "FK_c5220a47bc7878e72cb4e313421"`);
        await queryRunner.query(`ALTER TABLE "communication" DROP CONSTRAINT "FK_6fdd6bffa041d6a6b4c0184ccbf"`);
        await queryRunner.query(`ALTER TABLE "invitation" DROP CONSTRAINT "FK_757968494b8501e4e3b27860fb0"`);
        await queryRunner.query(`ALTER TABLE "invitation" DROP CONSTRAINT "FK_603764233ba5c97400836665523"`);
        await queryRunner.query(`ALTER TABLE "transcript" DROP CONSTRAINT "FK_2ede2eb745d7ea378687fcb7b35"`);
        await queryRunner.query(`ALTER TABLE "interview" DROP CONSTRAINT "FK_35c375805d4e8809adf67f635bb"`);
        await queryRunner.query(`ALTER TABLE "livekit_rooms" DROP CONSTRAINT "FK_ee8019347b8669627b2ac90a04e"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_56bd5315980a6bcd995a54df8fe"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_dbc0341504212f830211b69ba0c"`);
        await queryRunner.query(`ALTER TABLE "application_note" DROP CONSTRAINT "FK_5f195f30a2aa3160d902c186c6b"`);
        await queryRunner.query(`ALTER TABLE "application_note" DROP CONSTRAINT "FK_546f9c0eff39484764e5fe09290"`);
        await queryRunner.query(`ALTER TABLE "notification_settings" DROP CONSTRAINT "FK_5a8ffc3b89343043c9440d631e2"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_1ced25315eb974b73391fb1c81b"`);
        await queryRunner.query(`ALTER TABLE "saved_job" DROP CONSTRAINT "FK_ceb2154a962ca924a284f15c2e7"`);
        await queryRunner.query(`ALTER TABLE "saved_job" DROP CONSTRAINT "FK_65314280f947dd20a26faf013d2"`);
        await queryRunner.query(`ALTER TABLE "api_key" DROP CONSTRAINT "FK_277972f4944205eb29127f9bb6c"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_86586021a26d1180b0968f98502"`);
        await queryRunner.query(`ALTER TABLE "candidate_profile" DROP CONSTRAINT "FK_ab092d6b881f23c10ff1b801829"`);
        await queryRunner.query(`ALTER TABLE "cv" DROP CONSTRAINT "FK_68b505eded7c9f3add3afe9ff66"`);
        await queryRunner.query(`ALTER TABLE "education" DROP CONSTRAINT "FK_020a2f7db1c68a2d9eb9fe8c09d"`);
        await queryRunner.query(`ALTER TABLE "work_experience" DROP CONSTRAINT "FK_fe64019bc2a32b29226442f7342"`);
        await queryRunner.query(`ALTER TABLE "company" DROP CONSTRAINT "FK_3737905699894299444476dd79c"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_49dd92c00fe0d00a40602e2e171"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_e66170573cabd565dab1132727d"`);
        await queryRunner.query(`ALTER TABLE "saved_job" DROP CONSTRAINT "UQ_e78c19878d2e6143e4c6140c81c"`);
        await queryRunner.query(`ALTER TABLE "saved_job" DROP COLUMN "notes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99e589da8f9e9326ee0d01a028"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ec936941eb8556fcd7a1f0eae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_password_reset_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_password_reset_email"`);
        await queryRunner.query(`DROP TABLE "password_reset"`);
        await queryRunner.query(`DROP TABLE "whats_app_message"`);
        await queryRunner.query(`DROP TYPE "public"."whats_app_message_status_enum"`);
        await queryRunner.query(`DROP TABLE "communication"`);
        await queryRunner.query(`DROP TYPE "public"."communication_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."communication_direction_enum"`);
        await queryRunner.query(`DROP TYPE "public"."communication_type_enum"`);
        await queryRunner.query(`DROP TABLE "invitation"`);
        await queryRunner.query(`DROP TYPE "public"."invitation_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invitation_usertype_enum"`);
        await queryRunner.query(`DROP TABLE "database_backups"`);
        await queryRunner.query(`DROP TYPE "public"."database_backups_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."database_backups_status_enum"`);
        await queryRunner.query(`DROP TABLE "transcript"`);
        await queryRunner.query(`DROP TABLE "interview"`);
        await queryRunner.query(`DROP TYPE "public"."interview_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."interview_type_enum"`);
        await queryRunner.query(`DROP TABLE "livekit_rooms"`);
        await queryRunner.query(`DROP TABLE "application"`);
        await queryRunner.query(`DROP TYPE "public"."application_status_enum"`);
        await queryRunner.query(`DROP TABLE "application_note"`);
        await queryRunner.query(`DROP TABLE "notification_settings"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e78c19878d2e6143e4c6140c81"`);
        await queryRunner.query(`DROP TABLE "saved_job"`);
        await queryRunner.query(`DROP TABLE "live_kit_room"`);
        await queryRunner.query(`DROP TABLE "security_log"`);
        await queryRunner.query(`DROP TABLE "api_key"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_usertype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_candidate_profile_availability"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_candidate_profile_phone"`);
        await queryRunner.query(`DROP TABLE "candidate_profile"`);
        await queryRunner.query(`DROP TYPE "public"."candidate_profile_preferredworktype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."candidate_profile_availability_enum"`);
        await queryRunner.query(`DROP TABLE "cv"`);
        await queryRunner.query(`DROP TABLE "education"`);
        await queryRunner.query(`DROP TABLE "work_experience"`);
        await queryRunner.query(`DROP TABLE "company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb1c7d9ea827ecf0c54d079446"`);
        await queryRunner.query(`DROP TABLE "job"`);
        await queryRunner.query(`DROP TYPE "public"."job_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."job_worktype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."job_joblevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."job_type_enum"`);
        await queryRunner.query(`DROP TABLE "address"`);
    }

}
